apiVersion: carto.run/v1alpa1
kind: Workload
metadata:
  name: gpt3_jsm
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: gpt3_jsm
    apps.tanzu.vmware.com/has-tests: true
  annotations:
    autoscaling.knative.dev/minScale: '1'
spec:
  source:
    git:
      url: git-source-url
      ref:
        branch: main
