apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: gpt3-jsm
  labels:
    app.kubernetes.io/part-of: gpt3-jsm
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    # networking.knative.dev/visibility: cluster-local
  annotations:
    autoscaling.knative.dev/minScale: '1'
spec:
  source:
    git:
      url: 'https://github.com/jianhuabi/gpt3_jsm'
      ref:
        branch: main
